---
title: "loops_and_functions.qmd"
author: "kaiju"
format: html
---

```{r}
weekdays <- c("monday","tuesday","wednesday","thursday","friday","saturday","sunday")
transects <- c("transect A", "transect B", "transect C")


week_matrix <- matrix( nrow = length(weekdays), ncol = length(transects))

for (i in seq_along(transects)){
  for (j in seq_along(weekdays)){
  week_matrix[j,i] <- paste(weekdays[j],"-",transects[i])
  }
}

```

# Task 2
```{r}
force <- function( mass, acceleration){
  F <- mass * acceleration
  return(paste("the resulting force is", F,"Newtons"))
}

force(mass = 3, acceleration = 3)

```

# Task 3

```{r}
fish_parms <- data.frame(sci_name = c("chanos chanos",
                         "sphyraena barracuda",
                         "caranx ignobilis"), common_name = c("milkfish","great barracuda","giant trevally"), a_est = c(0.0905, 0.0181, 0.0353), b_est = c(2.52, 3.27, 3.05))

  
fish_weight <- function(fish_name, tot_length){
 data <- filter(fish_parms,common_name == fish_name)
  a <- data$a_est
  b <- data$b_est
  w = a*(tot_length)^b
  print(w)
}

fish_weight("great barracuda",10)
 
# ----
 l <- seq(from = 0, to = 100, by = 1)
results <- fish_weight("great barracuda", l)

```

# Task 4

```{r}
wave_power <- function( H, T){
  P = 0.5 * (H^2) * T
  return(P)
}
wave_power(3,8)

H_vec <- seq(from = 0, to = 3, by =0.2)
wave_power(H_vec, 8)
```









